"""ChallanPaymentParams: validated job parameters for the challan-payment
runner.

Contract with api/src/routes/challanPaymentRun.ts:
    required: vehicleNumber, challanNo, requestId
    optional: chassisNo, engineNo, phoneNo, department, driverId, source

Conventions (mirrors ChallanSettlementParams / PucParams):
  - ONE JOB PER CHALLAN. requestId is the AUTOGENERATED Firestore doc id of the
    record we write, and is the only thing that addresses it:

        subChallanRequests/{requestId}

    It is NOT the challan number. Every challan does have its own doc, but the
    doc id is a Firestore auto-id ("gzvLTgBXlyVOcT1IOhNK"), so requestId is
    opaque, CASE-SENSITIVE, and must round-trip byte-for-byte. Never normalize
    it and never derive it from anything.
  - challanNo is what the portal is searched with and what makes a log line
    readable. It is data ON the doc, never its address.
  - vehicleNumber is no longer a parent doc key (the doc is top-level). It is
    still required: the portal flow and the receipt's GCS path both need it.
  - driverId defaults to "na": the subChallan doc is keyed by vehicle+challan,
    but /api/internal/job-completed still requires a non-empty driverId.
  - phoneNo / chassisNo are optional at the type level only — the open_record
    phase aborts with a readable message when either is missing, because the
    portal's verification step needs both.
"""

from __future__ import annotations

import re
from typing import Literal

from pydantic import BaseModel, Field, field_validator


def normalize_id(s: str) -> str:
    """Canonical form used for matching challan/vehicle identifiers."""
    return re.sub(r"[^A-Za-z0-9]", "", str(s or "")).upper()


class ChallanPaymentParams(BaseModel):
    # ── required ──────────────────────────────────────────────────────────
    requestId: str = Field(min_length=1)  # subChallanRequests doc id (auto-id)
    vehicleNumber: str = Field(min_length=4, max_length=20)
    challanNo: str = Field(min_length=1)

    # ── optional ──────────────────────────────────────────────────────────
    chassisNo: str | None = None
    engineNo: str | None = None
    phoneNo: str | None = None
    # If provided, used VERBATIM as the Virtual Courts "Select Department"
    # option text. Omitted -> derived from the challan prefix by
    # tasks.challan_payment.departments.department_for_payment.
    department: str | None = None

    # ── plumbing ──────────────────────────────────────────────────────────
    driverId: str = "na"
    source: Literal["app", "web"] = "web"

    # ── validators ────────────────────────────────────────────────────────
    @field_validator("vehicleNumber")
    @classmethod
    def _normalize_vehicle(cls, v: str) -> str:
        n = normalize_id(v)
        if not (4 <= len(n) <= 12):
            raise ValueError(f"vehicle number '{v}' normalizes to '{n}' (bad length)")
        return n

    @field_validator("challanNo", "requestId")
    @classmethod
    def _strip(cls, v: str) -> str:
        # NOT normalized, and never will be: requestId is a case-sensitive
        # Firestore doc id and must round-trip to exactly what the client
        # wrote. Uppercasing it addresses a different (nonexistent) document.
        return (v or "").strip()

    @field_validator("phoneNo")
    @classmethod
    def _normalize_phone(cls, v: str | None) -> str | None:
        if not v:
            return None
        digits = re.sub(r"\D", "", v)
        return digits[-10:] if digits else None  # strips +91 / spaces

    @field_validator("driverId", mode="before")
    @classmethod
    def _default_driver(cls, v) -> str:
        s = str(v or "").strip()
        return s if s else "na"

    # ── helpers ───────────────────────────────────────────────────────────

    def chassis_last4(self) -> str:
        return (self.chassisNo or "").strip()[-4:]

    @classmethod
    def from_job(cls, raw: dict) -> "ChallanPaymentParams":
        return cls(**raw)
